# ============================================================
# Apache MPM Event Config
# Adjust values by server size and performance test result.
# ============================================================

<IfModule mpm_event_module>
    StartServers             4
    MinSpareThreads          100
    MaxSpareThreads          500
    ThreadsPerChild          50
    MaxRequestWorkers        1000
    MaxConnectionsPerChild   10000
</IfModule>
